In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

print(np.__version__)

2.2.4


In [19]:
data = [1, 2.222, 3, 4, 5]
arr_from_list = np.array(data)

print(arr_from_list)
print(type(arr_from_list))
print(arr_from_list.dtype)
print(arr_from_list.size)
print(arr_from_list.ndim)


print(np.zeros(5))

print(np.ones(4))

print(np.ones((4, 5)))

[1.    2.222 3.    4.    5.   ]
<class 'numpy.ndarray'>
float64
5
1
[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# np.full là hàm dùng để tạo một mảng với tất cả các phần tử đều có cùng một giá trị xác định. Cú pháp:
# np . full ( shape , fill_value )

print(np.full((4, 5), 9))

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [21]:
print(np.arange(-10, 10, 0.5))

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


In [22]:
# tạo ma trận đơn vị với np.eye
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:

np.random.seed(2025)

rand_arr = np.random.rand(2, 3)
print(rand_arr)

[[0.13548816 0.8878517  0.93260564]
 [0.44556816 0.38823555 0.25759644]]


In [28]:
# np.random.randint(low, hight, size)

print(np.random.randint(1, 100, (4, 5)))

[[78 58 83 72 30]
 [42 18 52 44 71]
 [ 9 25 46 75 23]
 [98 14 40  7 40]]


In [35]:
arr1d = np.array([1 , 2 , 3 , 4 , 5])
slice_arr1d = arr1d[-2:]

print (" Sclicing arr1d từ chỉ số 1 đến 3:",
slice_arr1d )


 Sclicing arr1d từ chỉ số 1 đến 3: [4 5]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

new = arr[1:, 1:]
print(new)

[[5 6]
 [8 9]]


In [43]:
# hàm hstack, vstack, concatenate
# nối các mảng theo hướng khác nhau 

a1 = [1, 2, 3]
a2 = [4, 5, 6]

np.hstack((a1, a2)) # nối mảng theo chiều ngang
np.vstack((a1, a2)) # nối theo chiều dọc như ma trận

np.vstack((a1, a2, a2))

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [49]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.concatenate((a1, a2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [8]:
# slicing, expand_dims
import numpy as np
# điều chỉnh số chiều của ma trận
# 1D -> 2D
a = np.array([1, 2, 3, 4, 5])

a = a[np.newaxis, :]
print(a)

a = a[np.newaxis, :]
print(a)

[[1 2 3 4 5]]
[[[1 2 3 4 5]]]


In [15]:
# reshape in numpy

a = np.array([1, 2, 3, 4, 5, 6])

a = np.reshape(a, shape=(2, 3))
print(a)



[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
# numpy where -> return the index 
a = np.array([1, 2, 3, 4])
# if any item > 2 -> return double , else divide by 2
print(np.where(a>2, a * 2, a /2))




[0.5 1.  6.  8. ]


In [3]:
# find max, min in array

import numpy as np

arr = np.array([1, 2, 3, 4])
print(np.max(arr))
print(np.min(arr))

4
1


In [6]:
arr2d = np.array([[1, 2, 3], [4, 9, 2]])

print(np.max(arr2d, axis=0))
print(np.max(arr2d, axis=1))
print("Min")
print(np.min(arr2d, axis=0))
print(np.min(arr2d, axis=1))

[4 9 3]
[3 9]
Min
[1 2 2]
[1 2]


In [ ]:
# Find the index of an array or matrix with
# np.argmax(), np.argmin

a2 = np.array([[1, 2, 3], [3, 1, 99]])

print(np.argmax(a2, axis=1))
print(np.argmax(a2, axis=0))




[2 2]
[1 0 1]


In [19]:
# sort
a = np.array([55, 3, 3, 4, 5])
print(np.sort(a))

ar = np.array([[7, 1, 2], [6, 5, 4]])

sted = np.sort(ar)
print(f'Sort default: {sted}')

print(f'sort by column: {np.sort(ar, axis=0)}')
# a3 = np.array([[[44, 2], [22, 2]], [[11, 2], [1, 222]]])

# print(a3.shape)

# print(np.sort(a3))



[ 3  3  4  5 55]
Sort default: [[1 2 7]
 [4 5 6]]
sort by column: [[6 1 2]
 [7 5 4]]


In [22]:
# substract array + add + multiply array
# + divide

# Or simply using operator like + - * / 

a1 = [1, 2, 3]
a2 = [2, 3, 4]
print(a1 + a2)

# dif

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)

[1, 2, 3, 2, 3, 4]
[5 7 9]


In [23]:
# inner product 
# Phep tinh tich vo huong 
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(np.dot(a1, a2))


32


In [ ]:
# Matrix-matrix multiplication
# using matmul

import numpy as np

a1 = np.array([[1, 2, 3], [2, 3, 4]])
a2 = np.array([[2, 3, ], [2, 3],[3, 2]])
# 2 x 3 + 3 x 2 = 2 x 2
print(np.matmul(a1, a2))


[[15 15]
 [22 23]]


In [8]:
# transpose - matrix
# convert column to row and row to column
# m x n => n x m

# assume you have an matrix here 
a = np.array([[1, 2, 3], [4, 5, 6]])

print(np.transpose(a))


# (A + B)^T = A^T + B^T

# (AB)^T = B^T*A^T

print(f'Transpose matrix \n:{a.T}')

[[1 4]
 [2 5]
 [3 6]]
Transpose matrix 
:[[1 4]
 [2 5]
 [3 6]]


In [11]:
# summation 
# np.sum(a, axis=None, dtype=None, keepdims=False, initial=0, where=True)

arr = np.array([[1 , 2 , 3] , [4 , 5 , 6]])

column_sum = np.sum( arr , axis =0)
row_sum = np.sum ( arr , axis =1)

print(column_sum)
print(row_sum)


[5 7 9]
[ 6 15]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(f'Sum of array: {np.sum(arr)}')

mean_value = np.mean(arr)
print(f'Mean value: {mean_value} = {np.sum(arr)}/{np.size(arr)}')



Sum of array: 15
Mean value: 3.0 = 15/5


In [16]:
# caculate the euclid distance vector

# using np.linalg.norm

# = sqrt(1^2 + 2^2 + 3^2)

vector = np.array([1, 2, 3])

norm = np.linalg.norm(vector)

print(f"Distance of an vector: {norm}")

Distance of an vector: 3.7416573867739413


In [17]:
# solve linear equation Ax = b

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
# linear algorithm
x = np.linalg.solve(A, b)

print("Solutions x:", x)

Solutions x: [2. 3.]


In [19]:
# broadcasting, function 
# broadcasting allow you to using some opearator 
# with array has diff size

# if matrix isn't match the dimension the operation will automatically expand the dimension in which matrix has smaller size

a = np.array([1, 2, 3])

result  = a + 2

print(f'Basic case:{result}')

Basic case:[3 4 5]


In [23]:
a2d = np.array([[1, 2, 3], [4, 5, 6]])
a1d = np.array([1, 2, 3])

result = a2d + a1d

print("matrix 1d:", a1d)
print("matrix 2d:", a2d)

print("Result: \n", result)

matrix 1d: [1 2 3]
matrix 2d: [[1 2 3]
 [4 5 6]]
Result: 
 [[2 4 6]
 [5 7 9]]


In [25]:
# apply_along_axis() 
# this func will apply all value in a row or column with function passby


def sum_of_elements(arr):
    return np.sum(arr)

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result = np.apply_along_axis(sum_of_elements, axis=1, arr=arr2d)

print("Sum of element in each row: ", result)


result = np.apply_along_axis(sum_of_elements, axis=0, arr=arr2d)

print("Sum of element in each column: ", result)

Sum of element in each row:  [ 6 15 24]
Sum of element in each column:  [12 15 18]


In [26]:
# vectorize

# convert the func to vectorize then it 
# can change each element with func 

# np.vectorize(func)

def celsius_to_fahrenheit(c):
    return (c * 9/5) + 32

vt  = np.vectorize(celsius_to_fahrenheit)

celsius = np.array([0, 20, 37, 100])

fahrenheit= vt(celsius)

print(f'Convert C to F:', fahrenheit)

Convert C to F: [ 32.   68.   98.6 212. ]
