In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

print(np.__version__)

2.2.4


In [19]:
data = [1, 2.222, 3, 4, 5]
arr_from_list = np.array(data)

print(arr_from_list)
print(type(arr_from_list))
print(arr_from_list.dtype)
print(arr_from_list.size)
print(arr_from_list.ndim)


print(np.zeros(5))

print(np.ones(4))

print(np.ones((4, 5)))

[1.    2.222 3.    4.    5.   ]
<class 'numpy.ndarray'>
float64
5
1
[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# np.full là hàm dùng để tạo một mảng với tất cả các phần tử đều có cùng một giá trị xác định. Cú pháp:
# np . full ( shape , fill_value )

print(np.full((4, 5), 9))

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [21]:
print(np.arange(-10, 10, 0.5))

[-10.   -9.5  -9.   -8.5  -8.   -7.5  -7.   -6.5  -6.   -5.5  -5.   -4.5
  -4.   -3.5  -3.   -2.5  -2.   -1.5  -1.   -0.5   0.    0.5   1.    1.5
   2.    2.5   3.    3.5   4.    4.5   5.    5.5   6.    6.5   7.    7.5
   8.    8.5   9.    9.5]


In [22]:
# tạo ma trận đơn vị với np.eye
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:

np.random.seed(2025)

rand_arr = np.random.rand(2, 3)
print(rand_arr)

[[0.13548816 0.8878517  0.93260564]
 [0.44556816 0.38823555 0.25759644]]


In [28]:
# np.random.randint(low, hight, size)

print(np.random.randint(1, 100, (4, 5)))

[[78 58 83 72 30]
 [42 18 52 44 71]
 [ 9 25 46 75 23]
 [98 14 40  7 40]]


In [35]:
arr1d = np.array([1 , 2 , 3 , 4 , 5])
slice_arr1d = arr1d[-2:]

print (" Sclicing arr1d từ chỉ số 1 đến 3:",
slice_arr1d )


 Sclicing arr1d từ chỉ số 1 đến 3: [4 5]


In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

new = arr[1:, 1:]
print(new)

[[5 6]
 [8 9]]


In [43]:
# hàm hstack, vstack, concatenate
# nối các mảng theo hướng khác nhau 

a1 = [1, 2, 3]
a2 = [4, 5, 6]

np.hstack((a1, a2)) # nối mảng theo chiều ngang
np.vstack((a1, a2)) # nối theo chiều dọc như ma trận

np.vstack((a1, a2, a2))

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [49]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.concatenate((a1, a2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [8]:
# slicing, expand_dims
import numpy as np
# điều chỉnh số chiều của ma trận
# 1D -> 2D
a = np.array([1, 2, 3, 4, 5])

a = a[np.newaxis, :]
print(a)

a = a[np.newaxis, :]
print(a)

[[1 2 3 4 5]]
[[[1 2 3 4 5]]]


In [15]:
# reshape in numpy

a = np.array([1, 2, 3, 4, 5, 6])

a = np.reshape(a, shape=(2, 3))
print(a)



[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
# numpy where -> return the index 
a = np.array([1, 2, 3, 4])
# if any item > 2 -> return double , else divide by 2
print(np.where(a>2, a * 2, a /2))




[0.5 1.  6.  8. ]


In [3]:
# find max, min in array

import numpy as np

arr = np.array([1, 2, 3, 4])
print(np.max(arr))
print(np.min(arr))

4
1


In [6]:
arr2d = np.array([[1, 2, 3], [4, 9, 2]])

print(np.max(arr2d, axis=0))
print(np.max(arr2d, axis=1))
print("Min")
print(np.min(arr2d, axis=0))
print(np.min(arr2d, axis=1))

[4 9 3]
[3 9]
Min
[1 2 2]
[1 2]


In [ ]:
# Find the index of an array or matrix with
# np.argmax(), np.argmin

a2 = np.array([[1, 2, 3], [3, 1, 99]])

print(np.argmax(a2, axis=1))
print(np.argmax(a2, axis=0))




[2 2]
[1 0 1]


In [19]:
# sort
a = np.array([55, 3, 3, 4, 5])
print(np.sort(a))

ar = np.array([[7, 1, 2], [6, 5, 4]])

sted = np.sort(ar)
print(f'Sort default: {sted}')

print(f'sort by column: {np.sort(ar, axis=0)}')
# a3 = np.array([[[44, 2], [22, 2]], [[11, 2], [1, 222]]])

# print(a3.shape)

# print(np.sort(a3))



[ 3  3  4  5 55]
Sort default: [[1 2 7]
 [4 5 6]]
sort by column: [[6 1 2]
 [7 5 4]]


In [22]:
# substract array + add + multiply array
# + divide

# Or simply using operator like + - * / 

a1 = [1, 2, 3]
a2 = [2, 3, 4]
print(a1 + a2)

# dif

a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(a1 + a2)

[1, 2, 3, 2, 3, 4]
[5 7 9]


In [23]:
# inner product 
# Phep tinh tich vo huong 
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

print(np.dot(a1, a2))


32


In [ ]:
# Matrix-matrix multiplication