<a href="https://colab.research.google.com/github/CN-LEON-DX/AI/blob/main/1_Numpy_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# create a list
lst = ["FuzzyFox", 2025, 3.14, True, [1, 2, 3]]
print("List:", lst)

for i in lst:
  print(f"Value {i} has type {type(i)}")

List: ['FuzzyFox', 2025, 3.14, True, [1, 2, 3]]
Value FuzzyFox has type <class 'str'>
Value 2025 has type <class 'int'>
Value 3.14 has type <class 'float'>
Value True has type <class 'bool'>
Value [1, 2, 3] has type <class 'list'>


In [ ]:
import numpy as np

arr = np.array([1, 4, 0, 1, 2, 0, 0,  4])
arr_zeros = np.zeros(5) # make 5 element has value 5

# convert list to np array
org_list = [1, 4, 2, 4]
list_to_numpy_arr = np.array(org_list)

print(arr)
print(arr_zeros)
print(list_to_numpy_arr)

[1 4 0 1 2 0 0 4]
[0. 0. 0. 0. 0.]
[1 4 2 4]


In [1]:
lst = [1, 4, 0, 1, 2, 0, 0, 4]

# forward index: 0, 1, 2, 3, 4, 5, 6, 7
# backward index: -6, -5, -4, -3, -2, -1

print("lst[2]=", lst[2])
print("lst[-4]=", lst[-4])

lst[2]= 0
lst[-4]= 2


In [3]:
import numpy as np
np_arr = np.array([1, 4, 0, 1, 2, 0, 0, 4])

# forward index: 0, 1, 2, 3, 4, 5, 6, 7
# backward index: -6, -5, -4, -3, -2, -1

print("np_arr[2]=", np_arr[2])
print("np_arr[-4]=", np_arr[-4])

np_arr[2]= 0
np_arr[-4]= 2


In [7]:
import numpy as np

lst = [10, 20, 30, 40]
np_arr = np.array(lst)


# Work with numpy
np_arr[[1, 2]]      # ✅ array([20, 30])

array([20, 30])

In [14]:
lst = [1, 2, 3, 4, 5, 6, 7]
    #  0, 1, 2, 3, 4, 5, 6
    # -7,-6,-5,-4,-3,-2,-1
# lst[start:end:step] => get elemend index from start -> end - 1
# and next index to get = current + step
print("case 1:",lst[1:6:2])
print("case 2:",lst[1:999:2])
print("case 3:",lst[-2:6:2])
print("case 4:",lst[-2:3:1])
print("case 5:",lst[:6:1])
print("case 6:",lst[::2])
print("case 7:",lst[2:4])


case 1: [2, 4, 6]
case 2: [2, 4, 6]
case 3: [6]
case 4: []
case 5: [1, 2, 3, 4, 5, 6]
case 6: [1, 3, 5, 7]
case 7: [3, 4]


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print("org:", arr)
b = arr[1:4]
b[0] = 99 # we change b -> arr also change
print("we've changed b:", arr)


org: [1 2 3 4 5 6]
we've changed b: [ 1 99  3  4  5  6]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr = np.append(arr, 999)
print(arr)

# or insert
arr = np.insert(arr, 0, 666)
print(arr)

[  1   2   3   4   5   6 999]
[666   1   2   3   4   5   6 999]


In [14]:
lst = [1, 2, 3, 4, 5, 6]
lst[1] = 999
print(lst)

# val
lst.extend([2, 3])
print(lst)

[1, 999, 3, 4, 5, 6]
[1, 999, 3, 4, 5, 6, 2, 3]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[1] = 999
print(arr)

# numpy array don't use extend
# and if you not assign after append the array wont change anythings
np.append(arr, [2, 3])
print("It not change :",arr)
arr = np.append(arr, [2, 3])
print("after asign:", arr)

[  1 999   3   4   5   6]
It not change : [  1 999   3   4   5   6]
after asign: [  1 999   3   4   5   6   2   3]


In [27]:
lst1 = [2, 3]
lst2 = [8, 7]

added = lst1 + lst2
print(added)

# list x a number
mul2 = lst1 * 4
print(mul2) # it will duplicate into n times

# list x list not work
mul = lst1 * lst2
print(mul)


[2, 3, 8, 7]
[2, 3, 2, 3, 2, 3, 2, 3]


TypeError: can't multiply sequence by non-int of type 'list'

In [28]:
import numpy as np

arr1 = np.array([2, 3])
arr2 = np.array([8, 7])

added = arr1 + arr2
print("added:", added)

mul2 = arr1 * 4
print("mul2:", mul2)

mul = arr1 * arr2
print("mul:", mul)

added: [10 10]
mul2: [ 8 12]
mul: [16 21]


In [29]:
lst = [1, 4, 0, 1, 2, 0, 0, 4]

# ascending order
lst.sort()
print(lst)
# descending order
lst.sort(reverse=True)
print(lst)

[0, 0, 0, 1, 1, 2, 4, 4]
[4, 4, 2, 1, 1, 0, 0, 0]


In [31]:
arr = np.array([1, 4, 0, 1, 2, 0, 0, 4])

# ascending order
arr.sort()
print(arr)
# descending order but in numpy we
just have: sort then arr[::-1]
arr.sort()
arr = arr[::-1]
print(arr)

[0 0 0 1 1 2 4 4]
[4 4 2 1 1 0 0 0]


In [32]:
lst = [1, 2, 3, 4, 5, 6]
# del list[start:end]
del lst[1:3]
print(lst)

[1, 4, 5, 6]


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
# np.delete(arr, np.arange(start, end))
arr = np.delete(arr, np.arange(1, 3))
print(arr)

# or np.concatenate((arr[:1], arr[3:]))

[1 4 5 6]


INDEX

In [37]:
lst = [2, 1, 5, 6, 7, 9, 5]

# find the first index has value passby
print(lst.index(5))

2


In [42]:
arr = np.array([2, 1, 5, 6, 7, 9, 5])

# work with multi dimension of array
print(np.where(arr==5)) # it will return a tuple
print(np.where(arr==5)[0][0])

# case 2
a = np.array([[1, 2, 3],
              [4, 5, 5]])
print(np.where(a == 5))

# or just using:
idx = np.argmax(arr == 5)
print(idx)

(array([2, 6]),)
2
(array([1, 1]), array([1, 2]))
2


In [43]:
lst = [2, 1, 5, 6, 7, 9, 5]
print(lst.count(5))

copy_lst = lst.copy()
print(copy_lst)

2
[2, 1, 5, 6, 7, 9, 5]


In [48]:
lst = [2, 1, 5, 6, 7, 9, 5]
print(len(lst))
print(min(lst))
print(max(lst))

7
1
9


In [50]:
arr = np.array([2, 1, 5, 6, 7, 9, 5])
print(len(arr))
print(np.min(arr))
print(np.max(arr))
print(arr.shape)

7
1
9
(7,)


In [46]:
arr = np.array([2, 1, 5, 6, 7, 9, 5])
print(np.sum(arr==5))

#copy
cp = arr.copy()
print(cp)

2
[2 1 5 6 7 9 5]


In [51]:
lst = [2, 1, 5, 6, 7, 9, 5]
print(sum(lst))

35


In [58]:
arr = np.array([2, 1, 5, 6, 7, 9, 5])
print(np.sum(arr))

print("Sum all element has value > 5:",np.sum(arr[arr>5])) # bolean masking

35
Sum all element has value > 5: 22


In [59]:
lst1 = [1, 2, 3]
lst2 = ['a', 'b', 'c']

zipped = zip(lst1, lst2)
print(list(zipped))   # [(1, 'a'), (2, 'b'), (3, 'c')]


[(1, 'a'), (2, 'b'), (3, 'c')]


In [63]:
a = np.array([1, 2, 3, 4, 5])
print(a[[1, 3, -1]])
# Output: 2, 4

[2 4 5]


In [65]:
a = np.array([1, 2, 3, 4, 5])
print(a[a>3])
print(np.sum(a[a>3]))

[4 5]
9


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
#reshape
rs = arr.reshape(3, 3)
print(rs)
#but rs_err = arr.reshape(2, 3)
# Error: cannot reshape array of size 9 into shape (2,3)

# flatten
arr = np.array([[1, 2], [3, 4], [5, 6]])
print("Befor:", arr)
flat_rs = arr.flatten()
print("After:", flat_rs)

# concatenate
arr2 = np.array([[1, 2], [3, 4], [5, 6]])
cc = np.concatenate((arr, arr2))
print(cc)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Befor: [[1 2]
 [3 4]
 [5 6]]
After: [1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
